services: 
  api:
    build: .
    container_name: tibber-api
    ports:
      - 5000:80
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - HOSTNAME=${HOSTNAME}
      - POSTGRES_PASSWORD_FILE=${POSTGRES_PASSWORD_FILE}
    secrets:
      - postgres-password
  db:
    image: postgres
    container_name: tibber-postgres-db
    hostname: ${HOSTNAME}
    ports:
      - 5432:5432
    volumes:
      - ./scripts/create-table.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - HOSTNAME=${HOSTNAME}
      - POSTGRES_PASSWORD_FILE=${POSTGRES_PASSWORD_FILE}
    secrets:
      - postgres-password
secrets:
  postgres-password:
    file: ./postgres_password.txt